name: Deploy Flask Web App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Debug Secrets and Variables
      run: |
        echo "Checking Secrets and Variables..."
        echo "S3_BUCKET=${{ secrets.S3_BUCKET }}"
        echo "TF_OUTPUT_PATH=${{ secrets.TF_OUTPUT_PATH }}"

    - name: Download Terraform Outputs from S3
      run: |
        aws s3 cp s3://${{ secrets.S3_BUCKET }}/${{ secrets.TF_OUTPUT_PATH }} tf_outputs.txt
        ls -lah  # Debugging step to check if the file exists

    - name: Extract Terraform Outputs
      run: |
        # Remove Terraform debug messages and extract key-value pairs
        grep ' = ' tf_outputs.txt | sed 's/^.*output//' > cleaned_tf_outputs.txt

        # Extract values from cleaned file
        ECS_CLUSTER=$(grep "ecs_cluster_name" cleaned_tf_outputs.txt | awk -F ' = ' '{print $2}' | tr -d '"')
        TASK_DEF=$(grep "ecs_task_family" cleaned_tf_outputs.txt | awk -F ' = ' '{print $2}' | tr -d '"')
        ECS_SERVICE=$(grep "ecs_service_name" cleaned_tf_outputs.txt | awk -F ' = ' '{print $2}' | tr -d '"')
        CONTAINER_NAME=$(grep "container_name" cleaned_tf_outputs.txt | awk -F ' = ' '{print $2}' | tr -d '"')
        DYNAMODB_TABLE=$(grep "dynamodb_table_name" cleaned_tf_outputs.txt | awk -F ' = ' '{print $2}' | tr -d '"')

        echo "Extracted values:"
        echo "ECS_CLUSTER=$ECS_CLUSTER"
        echo "TASK_DEF=$TASK_DEF"
        echo "ECS_SERVICE=$ECS_SERVICE"
        echo "CONTAINER_NAME=$CONTAINER_NAME"
        echo "DYNAMODB_TABLE=$DYNAMODB_TABLE"

        # Save to GitHub Environment Variables
        echo "ECS_CLUSTER=$ECS_CLUSTER" >> $GITHUB_ENV
        echo "TASK_DEF=$TASK_DEF" >> $GITHUB_ENV
        echo "ECS_SERVICE=$ECS_SERVICE" >> $GITHUB_ENV
        echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
        echo "DYNAMODB_TABLE=$DYNAMODB_TABLE" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image to Amazon ECR
      id: build-image
      uses: docker/build-push-action@v6
      with:
        context: ./flask-webapp-service
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
        platforms: linux/amd64
        provenance: false

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition $TASK_DEF --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: $CONTAINER_NAME
        image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: $ECS_SERVICE
        cluster: $ECS_CLUSTER
        wait-for-service-stability: true
